###
POST http://localhost:5287/register
Content-Type: application/json

{
    "email":"gowthamd@gmail.com",
    "password":"Qwerty@123"
}

###
GET http://localhost:5287/api/auth

###
POST http://localhost:5287/login
Content-Type: application/json

{
    "email":"gowthamd@gmail.com",
    "password":"Qwerty@123"
}

###
GET http://localhost:5287/api/todo
Authorization: Bearer CfDJ8DgIlW363wFJtzWmx_ZxRRSGb3BhM9nJ4A9wcT37g4RXU6edvu41dBgS8pWAU9SyRzw69Sp9NJ-QHqv5RS0nA0wzhbfeUlTc42rYuUt1v8StUd1kWOWjBzTAbUrn-PdJChthTAhEtqbYmypUqbq0RP3zXeYppnE57vYPjoUjkODzQqxrKovS30JYnu3tlFsLwzAUDeetprsiOdvuCHCkvxxYXy7_9D8PDe7hEmLay2eSekba3ZPdAsUN9r-0iF_SEnKoruz8typvj9nadXvzczVBpNAWCoG8z_2gqsExisHqCg4E3l7az0lzU-2Z1dV7ELxdc3JSeUAGzOlhdqstATDNdNYyyUnfkqCk78z5ywgj-PUa4EfpxcpX2m-_URrNlj45JFYcha5QQKV1m4U_DU_4ywaWZiyAaohxtigYuOJzRMO3i_W569b3lsjXfesyOBswZOeUrZPxk_6vRwCwETkl5Z8MRezbgsKp195DcNkZs7zXu6GhgBSgs4ZnD2E1U9E_dKa0sxZ2lVmdpsudW2QvktcBHIEf5YwMVYCz86p_E2IfpSvmkiBafqUPIJo_V3rbgW0slvlQEmqhsWelOobOfIS3kj-anPprPQqlw2VfJYSVpWtt36VjgXD2fTeo_8v5-wMvb093ojdPQ1I6OuE

###
GET http://localhost:5287/api/todo/1
Authorization: Bearer CfDJ8DgIlW363wFJtzWmx_ZxRRSGb3BhM9nJ4A9wcT37g4RXU6edvu41dBgS8pWAU9SyRzw69Sp9NJ-QHqv5RS0nA0wzhbfeUlTc42rYuUt1v8StUd1kWOWjBzTAbUrn-PdJChthTAhEtqbYmypUqbq0RP3zXeYppnE57vYPjoUjkODzQqxrKovS30JYnu3tlFsLwzAUDeetprsiOdvuCHCkvxxYXy7_9D8PDe7hEmLay2eSekba3ZPdAsUN9r-0iF_SEnKoruz8typvj9nadXvzczVBpNAWCoG8z_2gqsExisHqCg4E3l7az0lzU-2Z1dV7ELxdc3JSeUAGzOlhdqstATDNdNYyyUnfkqCk78z5ywgj-PUa4EfpxcpX2m-_URrNlj45JFYcha5QQKV1m4U_DU_4ywaWZiyAaohxtigYuOJzRMO3i_W569b3lsjXfesyOBswZOeUrZPxk_6vRwCwETkl5Z8MRezbgsKp195DcNkZs7zXu6GhgBSgs4ZnD2E1U9E_dKa0sxZ2lVmdpsudW2QvktcBHIEf5YwMVYCz86p_E2IfpSvmkiBafqUPIJo_V3rbgW0slvlQEmqhsWelOobOfIS3kj-anPprPQqlw2VfJYSVpWtt36VjgXD2fTeo_8v5-wMvb093ojdPQ1I6OuE

###
POST http://localhost:5287/api/todo
Authorization: Bearer CfDJ8DgIlW363wFJtzWmx_ZxRRSGb3BhM9nJ4A9wcT37g4RXU6edvu41dBgS8pWAU9SyRzw69Sp9NJ-QHqv5RS0nA0wzhbfeUlTc42rYuUt1v8StUd1kWOWjBzTAbUrn-PdJChthTAhEtqbYmypUqbq0RP3zXeYppnE57vYPjoUjkODzQqxrKovS30JYnu3tlFsLwzAUDeetprsiOdvuCHCkvxxYXy7_9D8PDe7hEmLay2eSekba3ZPdAsUN9r-0iF_SEnKoruz8typvj9nadXvzczVBpNAWCoG8z_2gqsExisHqCg4E3l7az0lzU-2Z1dV7ELxdc3JSeUAGzOlhdqstATDNdNYyyUnfkqCk78z5ywgj-PUa4EfpxcpX2m-_URrNlj45JFYcha5QQKV1m4U_DU_4ywaWZiyAaohxtigYuOJzRMO3i_W569b3lsjXfesyOBswZOeUrZPxk_6vRwCwETkl5Z8MRezbgsKp195DcNkZs7zXu6GhgBSgs4ZnD2E1U9E_dKa0sxZ2lVmdpsudW2QvktcBHIEf5YwMVYCz86p_E2IfpSvmkiBafqUPIJo_V3rbgW0slvlQEmqhsWelOobOfIS3kj-anPprPQqlw2VfJYSVpWtt36VjgXD2fTeo_8v5-wMvb093ojdPQ1I6OuE
Content-Type: application/json

{
    "userId":"1",
    "description":"Go to LUNCH",
    "isCompleted":true
}


###
PUT http://localhost:5287/api/todo/1
Authorization: Bearer CfDJ8DgIlW363wFJtzWmx_ZxRRSGb3BhM9nJ4A9wcT37g4RXU6edvu41dBgS8pWAU9SyRzw69Sp9NJ-QHqv5RS0nA0wzhbfeUlTc42rYuUt1v8StUd1kWOWjBzTAbUrn-PdJChthTAhEtqbYmypUqbq0RP3zXeYppnE57vYPjoUjkODzQqxrKovS30JYnu3tlFsLwzAUDeetprsiOdvuCHCkvxxYXy7_9D8PDe7hEmLay2eSekba3ZPdAsUN9r-0iF_SEnKoruz8typvj9nadXvzczVBpNAWCoG8z_2gqsExisHqCg4E3l7az0lzU-2Z1dV7ELxdc3JSeUAGzOlhdqstATDNdNYyyUnfkqCk78z5ywgj-PUa4EfpxcpX2m-_URrNlj45JFYcha5QQKV1m4U_DU_4ywaWZiyAaohxtigYuOJzRMO3i_W569b3lsjXfesyOBswZOeUrZPxk_6vRwCwETkl5Z8MRezbgsKp195DcNkZs7zXu6GhgBSgs4ZnD2E1U9E_dKa0sxZ2lVmdpsudW2QvktcBHIEf5YwMVYCz86p_E2IfpSvmkiBafqUPIJo_V3rbgW0slvlQEmqhsWelOobOfIS3kj-anPprPQqlw2VfJYSVpWtt36VjgXD2fTeo_8v5-wMvb093ojdPQ1I6OuE
Content-Type: application/json

{
    "userId":"1",
    "description":"Go to Temple",
    "isCompleted":false
}

###
DELETE  http://localhost:5287/api/todo/3
Authorization: Bearer CfDJ8DgIlW363wFJtzWmx_ZxRRSGb3BhM9nJ4A9wcT37g4RXU6edvu41dBgS8pWAU9SyRzw69Sp9NJ-QHqv5RS0nA0wzhbfeUlTc42rYuUt1v8StUd1kWOWjBzTAbUrn-PdJChthTAhEtqbYmypUqbq0RP3zXeYppnE57vYPjoUjkODzQqxrKovS30JYnu3tlFsLwzAUDeetprsiOdvuCHCkvxxYXy7_9D8PDe7hEmLay2eSekba3ZPdAsUN9r-0iF_SEnKoruz8typvj9nadXvzczVBpNAWCoG8z_2gqsExisHqCg4E3l7az0lzU-2Z1dV7ELxdc3JSeUAGzOlhdqstATDNdNYyyUnfkqCk78z5ywgj-PUa4EfpxcpX2m-_URrNlj45JFYcha5QQKV1m4U_DU_4ywaWZiyAaohxtigYuOJzRMO3i_W569b3lsjXfesyOBswZOeUrZPxk_6vRwCwETkl5Z8MRezbgsKp195DcNkZs7zXu6GhgBSgs4ZnD2E1U9E_dKa0sxZ2lVmdpsudW2QvktcBHIEf5YwMVYCz86p_E2IfpSvmkiBafqUPIJo_V3rbgW0slvlQEmqhsWelOobOfIS3kj-anPprPQqlw2VfJYSVpWtt36VjgXD2fTeo_8v5-wMvb093ojdPQ1I6OuE
